[[redirects]]
  from = "https://cowork.progressbar.sk/robots.txt"
  to = "https://cowork.progressbar.sk/static/robots.txt"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
